tagFormat: '${version}'
repositoryUrl: git@github.com:tallnerds/howfast.git
plugins:
  - '@semantic-release/changelog'
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - '@semantic-release/git'
