version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/node
    working_directory: ~/repo

  save_cache: &save_cache
    restore_cache:
      key: v1-dependencies-{{ checksum "package.json" }}
      paths:
        - node_modules

  restore_cache: &restore_cache
    restore_cache:
      key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  test:
    <<: *container_config
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f7:b7:c6:d5:e7:74:c1:6f:cc:11:84:85:b3:02:16:5c"
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm run test

  release:
    <<: *container_config
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - run: npx semantic-release

workflows:
  version: 2
  build-and-publish:
    jobs:
      - release:
          filters:
            branches:
              only: main
