version: 2.1

references:
  container_config: &container_config
    docker:
      - image: circleci/node
    working_directory: ~/repo

  save_cache: &save_cache
    restore_cache:
      key: v1-dependencies-{{ checksum "package.json" }}
      paths:
        - node_modules

  restore_cache: &restore_cache
    restore_cache:
      key: v1-dependencies-{{ checksum "package.json" }}

commands:
  auth_npm:
    description: 'Setup NPM auth'
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

jobs:
  test:
    <<: *container_config
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm run test

  publish:
    <<: *container_config
    steps:
      - checkout
      - auth_npm
      - *restore_cache
      - run: npm install
      - run: npm publish

  release:
    <<: *container_config
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - run: npx semantic-release

workflows:
  version: 2
  build-and-publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

      - release:
          filters:
            branches:
              only: main
